spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:PUBLIC;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS PUBLIC
    username: sa
    password:
    schema: classpath:db/migration/V1__init.sql
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration
