spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: password
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration
