spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: password
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
    level:
        org.jooq.tools.LoggerListener: DEBUG
