spring:
  application:
    name: app
  datasource:
#    url: jdbc:postgresql://localhost:5432/mydatabase
#    username: myuser
#    password: secret
#    driver-class-name: org.postgresql.Driver
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true

flyway:
  enabled: true
  locations: classpath:db/migration